### PR TITLE
Remove pesky comma

### PR DESCRIPTION
**Pull request by marvinjason**
Title says it all lol

### CODE REVIEW

**Comment by deecewan** [comment]
@marvinjason what version of node are you using that you can't use trailing commas? I thought they were supported in 8+?

**Comment by marvinjason** [comment]
@daveallie should I revert this? Can confirm my issue is resolved by updating node. Apparently, my nvm config just got all messed up

**Comment by daveallie** [comment]
@deecewan marvin was running node 6. I couldn't remember if node 6 or 8 was pinned for development in payaus, but I feel like this was a useful change to make anyway. I'm not going to worry about publishing this version, but I don't think we should roll it back.

**Comment by daveallie** [comment]
Otherwise, we should make it more clear that we only support Node 8+ for this package

**Comment by deecewan** [comment]
yeah doesn't really phase me either was. I think that we should always be locked to the latest LTS, especially because we only rely on Node for tooling and not production services. If there is an `.nvmrc` in core, we should pin it to LTS.

**Comment by daveallie** [comment]
I think atm it's pinned to what CI is pinned to, we should take this discussion elsewhere, but I am pretty keen to just pin it to a specific version and go through the process of updating node in both CI/dev/prod at the same time when new LTS releases come out.

**Pull request merged**
